
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kienjbeckgfsajjxjqhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpZW5qYmVja2dmc2FqanhqcWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDEyMzgsImV4cCI6MjA1OTc3NzIzOH0.1oLiRxns07hocC9q6-Ma6q5GMqKzjxaVQcbx4LsKF8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
